### ISSUE TITLE
auto win?

### ISSUE THREAD

**Issue by Jaackla** [Ewoutvans/GameSpleef#1]
Using the latest version for sponge api7 on my pixelmon server tested it out and when we started it coutns down and teleports us to the 1st floor then gives someone an auto win as soon as we all get teleported up there?

**Comment by Ewoutvans** [comment]
I did some testing and everything seems to be working fine.
The way it works is that the plugin will look for the lowest floor defined (based on Y coordinate) and will 'kill' everybody below that Y-coordinate.
So my guess is that you didn't place the floors correct or your spawn correct try recreating the area if you still have problems provide me with the gamespleef.conf so I can look at the coordinates. 

I'm closing this issue because this doesn't seem as a plugin issue.
