### ISSUE TITLE
Getting Weird error

### ISSUE THREAD

**Issue by ghost** [Ewoutvans/GameSpleef#2]
When I go and click save I get Error occurred while executing the command: The box is degenerate on y

**Comment by Ewoutvans** [comment]
This is because you probably didn't set the coordinates correctly.
If you add a floor in the first corner go stand **on top of the floor** and on the other corner go stand 1 block **below the floor**.

I'm planning to make in future versions a check that tells you immediately when you are setting the area so this doesn't happen.

**Comment by yaroslav4167** [comment]
I did everything as indicated in the video instructions. But I have the same error.
![Error](http://bit.ly/2nunzmI)
